# Application Name
spring.application.name=feature-flag-service

# API Key — override with API_KEY env var in production
API_KEY=dev-key-local

# Server Port
server.port=8080

# Active Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
# TTL = 600000ms = 10 minutes (cache expires after 10 min)


# Actuator endpoints
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Run data.sql on startup
spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true