apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flag-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/featureflags"
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: "prod"