apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feature-flag-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: feature-flag.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feature-flag-service
                port:
                  number: 8080